---
- hosts: localhost
  vars:
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Log in
      kubernetes.core.k8s_auth:
        host: https://api.apps.dev.mdi.local:6443
        username: "{{ user }}"
        password: "{{ pass }}"
        validate_certs: false
      register: k8s_auth_results
    - name: Create NS
      kubernetes.core.k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        name: "{{ projName }}"
        kind: Namespace
        state: present
    - name: Role Binding for project/namespace
      k8s:
        state: present
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        definition:
          kind: RoleBinding
          metadata:
            name: project-admin
            namespace: "{{ projName }}"
          apiVersion: rbac.authorization.k8s.io/v1
          subjects:
            - kind: Group
              apiGroup: rbac.authorization.k8s.io
              name: "ms-dev"
              namespace: "{{ projName }}"
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin
            spec:
              finalizers:
                - kubernetes
              status:
                phase: Active
